# Set up the environment.
environment:
  # Run for both architectures for python 3.7.x
  matrix:
    - PYTHON: "C:\\Python312"

# Set the python path.
init:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%

# Installations.
install:
  # Upgrade pip to the latest version.
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r dev_requirements.txt

# Testing script.
test_script:
  # Test for python styles.
  - flake8
  - pydocstyle

  # Trigger unit test and find coverage.
  - pytest --cov=src

build: off
