# Set the language to be python and adjust the environment.
language: python
sudo: required

# Set the version of python to be the latest version.
python: "3.12"

# Installations.
install:
  # Upgrade pip to the latest version.
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r dev_requirements.txt

# Testing script.
script:
  # Test for python styles.
  - flake8
  - pydocstyle

  # Trigger unit test and find coverage.
  - pytest --cov=src

# Find code coverage.
after_success: codecov
